"""File collection for repository packs (docs/spec/part2.md 8c steps 2 to 4).

Filters in spec order: nested `.gitignore` chains and `.intomdignore` (pathspec gitwildmatch; the deepest
file with a matching rule wins, so negations in nested files work), default excludes (VCS, vendor, build
output, caches), credential-named files, binaries, oversize files, minified bundles and source maps, then the
user's include/exclude globs. Lockfiles are kept but truncated to 50 lines. Counts per reason feed the
sidecar and the tree.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import PurePosixPath

import pathspec

from intomd.core.textclean import CleanStats, clean_text
from intomd_converters.code.archive import Member
from intomd_converters.code.languages import language_for
from intomd_converters.code.secrets import is_secret_file
from intomd_converters.text.plain import decode_text_detailed

__all__ = ["Collected", "FileEntry", "collect"]

DEFAULT_EXCLUDED_DIRS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        "vendor",
        "dist",
        "build",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".next",
        ".gradle",
        ".idea",
    }
)
LOCKFILES = frozenset(
    {
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "pipfile.lock",
        "uv.lock",
        "pdm.lock",
        "cargo.lock",
        "gemfile.lock",
        "composer.lock",
        "go.sum",
        "mix.lock",
        "pubspec.lock",
        "packages.lock.json",
        "flake.lock",
        "bun.lockb",
    }
)
LOCKFILE_LINES = 50
MINIFIED_LINE_CHARS = 2000
MINIFIED_HEAD_CHARS = 2000
TEST_DIRS = frozenset({"test", "tests", "spec", "__tests__", "testing"})
_BINARY_SUFFIXES = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tif", ".tiff", ".psd", ".heic", ".avif",
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        ".zip", ".tar", ".gz", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".zst", ".jar", ".war", ".whl", ".egg",
        ".exe", ".dll", ".so", ".dylib", ".a", ".o", ".obj", ".lib", ".bin", ".class", ".pyc", ".pyo", ".wasm",
        ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".odt",
        ".mp3", ".mp4", ".wav", ".flac", ".ogg", ".mov", ".avi", ".mkv", ".webm", ".m4a",
        ".sqlite", ".db", ".pkl", ".npy", ".npz", ".parquet", ".onnx", ".pt", ".h5",
    }
)  # fmt: skip
_GENERATED_NAME = re.compile(r"(?:\.generated\.|_pb2(?:_grpc)?\.py$|\.pb\.go$|\.g\.dart$|\.designer\.cs$)")
_GENERATED_HEADER = re.compile(r"@generated|Code generated by|DO NOT EDIT|auto-generated", re.IGNORECASE)
_NUL = chr(0)


@dataclass(slots=True)
class FileEntry:
    path: str
    size: int
    text: str = ""
    language: str | None = None
    lines: int = 0
    excluded: str | None = None
    """Exclusion reason, or None when the file is packed."""
    lockfile: bool = False
    generated: bool = False
    minified: bool = False
    note: str | None = None
    """Inline marker appended inside the fence (lockfile or minified truncation)."""

    @property
    def depth(self) -> int:
        return self.path.count("/")

    @property
    def is_test(self) -> bool:
        parts = self.path.lower().split("/")[:-1]
        name = PurePosixPath(self.path).name.lower()
        return any(p in TEST_DIRS for p in parts) or name.startswith("test_") or ".test." in name or ".spec." in name


@dataclass(slots=True)
class Collected:
    files: list[FileEntry] = field(default_factory=list)
    """Every non-ignored file: packed ones (excluded None) and rule-excluded ones (shown in the tree)."""
    excluded_dirs: dict[str, int] = field(default_factory=dict)
    """Default-excluded directory path -> number of files under it."""
    reasons: Counter[str] = field(default_factory=Counter)
    clean: CleanStats = field(default_factory=CleanStats)

    @property
    def packed(self) -> list[FileEntry]:
        return [f for f in self.files if f.excluded is None]


def _globs(raw: object) -> pathspec.GitIgnoreSpec | None:
    if not isinstance(raw, str) or not raw.strip():
        return None
    return pathspec.GitIgnoreSpec.from_lines([p.strip() for p in raw.split(",") if p.strip()])


def _ignore_specs(members: list[Member]) -> dict[str, pathspec.GitIgnoreSpec]:
    """Directory ('' for root) -> combined spec of its .gitignore and .intomdignore."""
    by_dir: dict[str, list[str]] = {}
    for m in sorted(members, key=lambda x: (x.path.endswith(".intomdignore"), x.path)):
        name = PurePosixPath(m.path).name
        if name not in (".gitignore", ".intomdignore") or m.data is None:
            continue
        parent = str(PurePosixPath(m.path).parent)
        key = "" if parent == "." else parent
        by_dir.setdefault(key, []).extend(m.data.decode("utf-8", errors="replace").splitlines())
    return {d: pathspec.GitIgnoreSpec.from_lines(lines) for d, lines in by_dir.items()}


def _decision(parts: list[str], specs: dict[str, pathspec.GitIgnoreSpec], *, is_dir: bool) -> bool:
    """The last matching rule across the ignore files from the root down to the entry's own directory."""
    decision = False
    for i in range(len(parts)):
        spec = specs.get("/".join(parts[:i]))
        if spec is None:
            continue
        rel = "/".join(parts[i:]) + ("/" if is_dir else "")
        res = spec.check_file(rel)
        if res.include is not None:
            decision = res.include
    return decision


def _ignored(path: str, specs: dict[str, pathspec.GitIgnoreSpec]) -> bool:
    """Git semantics: a file under an ignored directory stays ignored even when a later `!negation` names it
    ("it is not possible to re-include a file if a parent directory of that file is excluded")."""
    parts = path.split("/")
    for k in range(1, len(parts)):
        if _decision(parts[:k], specs, is_dir=True):
            return True
    return _decision(parts, specs, is_dir=False)


def _excluded_dir(path: str) -> str | None:
    parts = path.split("/")[:-1]
    for i, p in enumerate(parts):
        if p in DEFAULT_EXCLUDED_DIRS:
            return "/".join(parts[: i + 1])
    return None


def collect(members: list[Member], options: dict[str, object], max_file_bytes: int, within: str = "") -> Collected:
    """`within` restricts packing to a subtree; ignore files above it still apply."""
    out = Collected()
    prefix = within.strip("/") + "/" if within.strip("/") else ""
    respect = options.get("respect_gitignore", True) is not False
    specs = _ignore_specs(members) if respect else {}
    include = _globs(options.get("include"))
    exclude = _globs(options.get("exclude"))
    for m in sorted(members, key=lambda x: x.path):
        if prefix and not m.path.startswith(prefix):
            continue
        xdir = _excluded_dir(m.path)
        if xdir is not None:
            out.excluded_dirs[xdir] = out.excluded_dirs.get(xdir, 0) + 1
            out.reasons["default_excluded"] += 1
            continue
        if specs and _ignored(m.path, specs):
            out.reasons["gitignored"] += 1
            continue
        if (include is not None and not include.match_file(m.path)) or (
            exclude is not None and exclude.match_file(m.path)
        ):
            out.reasons["user_excluded"] += 1
            continue
        entry = _classify(m, max_file_bytes, out.clean)
        if entry.excluded is not None:
            out.reasons[entry.excluded] += 1
        out.files.append(entry)
    return out


def _classify(m: Member, max_file_bytes: int, clean: CleanStats) -> FileEntry:
    name = PurePosixPath(m.path).name.lower()
    entry = FileEntry(path=m.path, size=m.size)
    head = (m.data or b"")[:4096].decode("utf-8", errors="replace")
    if is_secret_file(m.path, head):
        entry.excluded = "secret_file"
        return entry
    if PurePosixPath(name).suffix in _BINARY_SUFFIXES:
        entry.excluded = "binary"
        return entry
    if name.endswith((".min.js", ".min.css", ".map")):
        entry.excluded = "minified"
        return entry
    if m.data is None or m.size > max_file_bytes:
        entry.excluded = "too_large"
        return entry
    raw = m.data
    if raw[:8192].count(_NUL.encode()) and not raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        entry.excluded = "binary"
        return entry
    text, _enc, _uncertain, _conf = decode_text_detailed(raw)
    text = clean_text(text, clean)
    entry.language = language_for(m.path, text)
    entry.lockfile = name in LOCKFILES or name.endswith(".lock")
    entry.generated = bool(_GENERATED_NAME.search(name) or _GENERATED_HEADER.search("\n".join(text.split("\n")[:5])))
    lines = text.split("\n")
    if text.endswith("\n"):
        lines = lines[:-1]
    entry.lines = len(lines)
    if entry.lockfile and len(lines) > LOCKFILE_LINES:
        entry.note = f"... (lockfile truncated, {len(lines) - LOCKFILE_LINES:,} more lines)"
        text = "\n".join(lines[:LOCKFILE_LINES])
    elif any(len(line) > MINIFIED_LINE_CHARS for line in lines):
        entry.minified = True
        entry.note = f"... (minified, truncated, {max(0, len(text) - MINIFIED_HEAD_CHARS):,} more characters)"
        text = text[:MINIFIED_HEAD_CHARS]
    entry.text = text.rstrip("\n")
    return entry
