// GENERATED by packages/sdk-ts/scripts/generate.mjs from docs/api/openapi.json. Do not edit.
// Regenerate: `uv run python apps/api/scripts/export_openapi.py && pnpm -F @intomd/sdk generate`.

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description 200 whenever the process is serving requests. Does not check dependencies.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness: database, Redis, and a live worker
         * @description 200 when the database and state backend answer and a worker heartbeated in the last 60 s; else 503.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Converters, profiles, formats, limits, fetch-node status
         * @description Lists every registered converter (including ones whose optional extra is missing, with `loaded: false`), the output profiles and formats, the anonymous limits, and whether a residential fetch node is online. The web UI reads this on load.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a conversion job from an upload (multipart) or a URL (JSON)
         * @description Send `multipart/form-data` with a `file` part (and an optional `options` JSON part), or JSON with a `url`. Returns 202 with the job envelope, or 200 when an identical finished job is reused. URL inputs from anonymous callers need a Turnstile token when the instance requires one. With `wait=N` the call blocks up to N seconds (max 60) and returns the rendered result directly if the job finishes in time.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch-node/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim the next residential fetch job
         * @description Returns the oldest unclaimed `fetch_residential` job with a single-use claim token (valid 10 minutes, extended by heartbeats), or 204 when there is none. The URL is re-validated by the SSRF guard at claim time; `platform` and `resolved_ip` are hints the node must re-check itself.
         */
        post: operations["fetchNodeClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch-node/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a failed fetch with a reason code
         * @description Returns the job to the queue once; after that the job moves to `needs_user_action`.
         */
        post: operations["fetchNodeFail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch-node/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Liveness and capabilities; extends an active claim
         * @description Marks the node online for 60 s and, with `claim_token`, pushes that claim's expiry 10 minutes out.
         */
        post: operations["fetchNodeHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch-node/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload fetched media for a claimed job
         * @description Stores the media under the job and enqueues it on `media` (or `default`); consumes the claim token.
         */
        post: operations["fetchNodeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job state and metadata
         * @description State, progress, input metadata, warning codes, and, depending on the state, `needs_action` (what the client must supply) or `error`. Unknown ids and ids owned by another API key both return 404.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /**
         * Purge the job and its blobs now
         * @description Deletes the job row, its input, IR, rendered results, attachments, and buffered events.
         */
        delete: operations["deleteJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/attachments/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CSV sidecars and extracted images
         * @description A file the conversion produced (table CSVs, extracted images), by the relative path listed in the sidecar. Images are served inline; everything else as an attachment with `nosniff`.
         */
        get: operations["getJobAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events: progress, state, warning, done, failed, needs_user_action
         * @description A `text/event-stream` of numbered events: `state`, `progress`, `warning` (a Warning JSON), and one terminal `done`, `failed`, or `needs_user_action`, after which the stream closes. A `: keepalive` comment is sent every 15 s. Reconnect with `Last-Event-ID` (or `last_event_id`) to resume; the buffer keeps 500 events.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rendered output
         * @description The job's output in any profile and format, rendered from the cached IR (other profiles render on demand without re-converting). Extra query keys are profile overrides, flat (`max_tokens=2000`) or dotted (`chunks.chunk_tokens=512`). Markdown responses carry `X-Markdown-Tokens`, `X-Intomd-Truncated`, `X-Intomd-Warnings`, and `X-Intomd-Injection-Risk`. Returns 409 until the job is done.
         */
        get: operations["getJobResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/supply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supply a file or caption JSON for a needs_user_action job
         * @description When a job is in `needs_user_action` (for example no residential fetch node could fetch a video), upload the file as multipart `file`, or send caption JSON from the browser extension. The job returns to `queued`.
         */
        post: operations["supplyJobInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The warning code registry
         * @description Every warning code a conversion can emit, with its default severity, a description, a suggested action, whether it means content was truncated, and the retired spellings (aliases) that normalize to it. `JobOut.warnings`, SSE `warning` events, and the sidecar use these codes.
         */
        get: operations["listWarningCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CapabilitiesOut
         * @description What this instance can do (`GET /v1/capabilities`). Limits are the anonymous caps.
         */
        CapabilitiesOut: {
            /** Challenge */
            challenge?: "turnstile" | null;
            /** Converters */
            converters: components["schemas"]["ConverterOut"][];
            /** Fetch Node Online */
            fetch_node_online: boolean;
            /**
             * Formats
             * @example [
             *       "md",
             *       "json",
             *       "txt",
             *       "zip"
             *     ]
             */
            formats: string[];
            limits: components["schemas"]["LimitsOut"];
            /**
             * Profiles
             * @example [
             *       "full",
             *       "compact",
             *       "rag",
             *       "agent"
             *     ]
             */
            profiles: string[];
            /** Public Mode */
            public_mode: boolean;
            /** Residential Platforms */
            residential_platforms: string[];
            /** Turnstile Site Key */
            turnstile_site_key?: string | null;
            /**
             * Version
             * @example 0.0.1
             */
            version: string;
        };
        /** ConverterOut */
        ConverterOut: {
            /** Experimental */
            experimental: boolean;
            /**
             * Extras
             * @description pip extras that provide the converter's engine
             */
            extras: string[];
            /**
             * Family
             * @example text
             */
            family: string;
            /**
             * Id
             * @example text.markdown
             */
            id: string;
            /**
             * Loaded
             * @description False when the converter's optional extra is not installed
             */
            loaded: boolean;
            /** Mimes */
            mimes: string[];
        };
        /**
         * ConvertOptionsIn
         * @description Conversion options a client may set (a subset of `intomd.library.Options`; omitted fields use the library default). Dotted keys such as `chunks.chunk_tokens` are profile overrides and are accepted alongside these fields in the same object.
         */
        ConvertOptionsIn: {
            /**
             * Asr Model
             * @description Speech-recognition model id (for example `small`).
             * @default null
             * @example small
             */
            asr_model: string | null;
            /**
             * Comments
             * @description Include document comments.
             * @default null
             * @example true
             */
            comments: boolean | null;
            /**
             * Diarize
             * @description Label speakers in transcripts when supported.
             * @default null
             * @example true
             */
            diarize: boolean | null;
            /**
             * Extract Images
             * @description Extract embedded images as attachments.
             * @default null
             * @example true
             */
            extract_images: boolean | null;
            /**
             * Formulas
             * @description Keep spreadsheet formulas next to their values.
             * @default null
             * @example false
             */
            formulas: boolean | null;
            /**
             * Languages
             * @description BCP-47 language hints; empty means auto-detect.
             * @default null
             * @example [
             *       "en"
             *     ]
             */
            languages: string[] | null;
            /**
             * Max Duration Seconds
             * @description Audio/video duration cap in seconds; clamped to the caller's limit.
             * @default null
             * @example 900
             */
            max_duration_seconds: number | null;
            /**
             * Max Pages
             * @description Stop after this many pages; clamped to the caller's page limit.
             * @default null
             * @example 200
             */
            max_pages: number | null;
            /**
             * Ocr
             * @description Allow OCR when a page has no text layer.
             * @default null
             * @example true
             */
            ocr: boolean | null;
            /**
             * Tracked Changes
             * @description Include tracked insertions and deletions (Office).
             * @default null
             * @example true
             */
            tracked_changes: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ConvertResponse
         * @description The job envelope returned by `POST /v1/convert` (202, or 200 when deduplicated).
         */
        ConvertResponse: {
            /**
             * Deduplicated
             * @description True when an existing finished job with the same input was returned
             */
            deduplicated: boolean;
            job: components["schemas"]["JobOut"];
            links: components["schemas"]["LinksOut"];
        };
        /**
         * ConvertUrlRequest
         * @description JSON body of `POST /v1/convert` for a URL input.
         * @example {
         *       "options": {
         *         "max_pages": 100
         *       },
         *       "prefer_residential": false,
         *       "profile": "compact",
         *       "url": "https://example.com/reports/q3-fleet.pdf"
         *     }
         */
        ConvertUrlRequest: {
            /**
             * @description ConvertOptionsIn fields plus dotted profile overrides such as `chunks.chunk_tokens`.
             * @default {}
             */
            options: components["schemas"]["ConvertOptionsIn"];
            /**
             * Prefer Residential
             * @description Keyed callers with the residential permission only; ignored for anonymous callers (D-0017)
             * @default false
             */
            prefer_residential: boolean;
            /**
             * Profile
             * @description Output profile.
             * @default full
             * @enum {string}
             */
            profile: "full" | "compact" | "rag" | "agent";
            /**
             * Turnstile Token
             * @description Cloudflare Turnstile token; required for anonymous URL jobs.
             * @default null
             */
            turnstile_token: string | null;
            /**
             * Url
             * @description http(s) URL to fetch and convert. Private addresses are refused.
             */
            url: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Stable machine-readable code (see the table in the API description)
             */
            code: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /** Docs */
            docs: string;
            /**
             * Message
             * @description Human-readable; never contains stack traces or server paths
             */
            message: string;
            /**
             * Request Id
             * @description Matches the X-Request-Id response header
             */
            request_id: string;
            /** Status */
            status: number;
        };
        /**
         * ErrorResponse
         * @description The error schema of docs/spec/part1.md section 7.5.
         * @example {
         *       "error": {
         *         "code": "input_too_large",
         *         "detail": {
         *           "limit_bytes": 26214400
         *         },
         *         "docs": "https://intomd.example.com/docs/errors#input_too_large",
         *         "message": "Upload exceeds the 25 MB limit for anonymous requests.",
         *         "request_id": "req_3fQ9xL2mVb7Kp1Zt",
         *         "status": 413
         *       }
         *     }
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * FetchNodeClaimRequest
         * @example {
         *       "capabilities": [
         *         "yt-dlp",
         *         "ffmpeg"
         *       ],
         *       "max_duration_seconds": 10800,
         *       "node_id": "pi-home-1"
         *     }
         */
        FetchNodeClaimRequest: {
            /** Capabilities */
            capabilities?: string[];
            /** Max Duration Seconds */
            max_duration_seconds?: number | null;
            /** Node Id */
            node_id: string;
        };
        /** FetchNodeClaimResponse */
        FetchNodeClaimResponse: {
            /** Claim Expires At */
            claim_expires_at: string;
            /** Claim Token */
            claim_token: string;
            /** Job Id */
            job_id: string;
            /** Max Bytes */
            max_bytes: number;
            /** Max Duration Seconds */
            max_duration_seconds: number;
            /**
             * Platform
             * @description The platform-policy entry matching the URL's host (for example youtube.com)
             */
            platform?: string | null;
            /**
             * Resolved Ip
             * @description Address the VPS resolved and validated at claim time (null when DNS failed). Advisory: the node must re-run netguard itself before fetching (Phase 3).
             */
            resolved_ip?: string | null;
            /**
             * Upload Url
             * @example /v1/fetch-node/upload
             */
            upload_url: string;
            /** Url */
            url: string;
            /**
             * Want
             * @description audio, video, or page
             * @example audio
             */
            want: string;
        };
        /** FetchNodeFail */
        FetchNodeFail: {
            /** Claim Token */
            claim_token: string;
            /** Message */
            message?: string | null;
            /**
             * Reason Code
             * @example bot_check
             */
            reason_code: string;
        };
        /** FetchNodeHeartbeat */
        FetchNodeHeartbeat: {
            /** Capabilities */
            capabilities?: string[];
            /**
             * Claim Token
             * @description Extends this claim when present
             */
            claim_token?: string | null;
            /** Node Id */
            node_id: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** InputOut */
        InputOut: {
            /**
             * Display
             * @description File name or redacted URL
             * @example q3-fleet.pdf
             */
            display: string;
            /**
             * Kind
             * @description bytes, url, residential_fetch, or captions_json3
             * @example bytes
             */
            kind: string;
            /**
             * Mime
             * @description Detected media type
             * @example application/pdf
             */
            mime?: string | null;
            /**
             * Sha256
             * @description Input digest (uploads only, omitted on create)
             */
            sha256?: string | null;
            /**
             * Size Bytes
             * @example 1834022
             */
            size_bytes?: number | null;
        };
        /**
         * JobOut
         * @description A job's state and metadata (`GET /v1/jobs/{job_id}`).
         * @example {
         *       "converter_id": "text.markdown",
         *       "created_at": "2026-10-12T18:40:00Z",
         *       "expires_at": "2026-10-13T18:40:00Z",
         *       "id": "job_7Kx2mQp9Lw3nRt5vYb8cDe",
         *       "input": {
         *         "display": "notes.md",
         *         "kind": "bytes",
         *         "mime": "text/markdown",
         *         "size_bytes": 2048
         *       },
         *       "profile": "full",
         *       "progress": 100,
         *       "queue": "default",
         *       "stage_message": "Done",
         *       "state": "done",
         *       "truncated": false,
         *       "updated_at": "2026-10-12T18:40:02Z",
         *       "warnings": [
         *         "encoding_uncertain"
         *       ],
         *       "warnings_count": 1
         *     }
         */
        JobOut: {
            /**
             * Converter Id
             * @example documents.docling_pdf
             */
            converter_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Error
             * @description Present in failed: the error object (7.5)
             */
            error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Expires At
             * @description When the job and its results are purged
             */
            expires_at?: string | null;
            /**
             * Id
             * @description Unguessable job id; possession is the capability
             * @example job_7Kx2mQp9Lw3nRt5vYb8cDe
             */
            id: string;
            input: components["schemas"]["InputOut"];
            /**
             * Needs Action
             * @description Present in needs_user_action: what the client must supply and where
             */
            needs_action?: {
                [key: string]: unknown;
            } | null;
            /**
             * Profile
             * @description Requested profile
             * @example rag
             */
            profile: string;
            /**
             * Progress
             * @description Percent complete
             */
            progress: number;
            /**
             * Queue
             * @description default, media, fetch, or fetch_residential
             * @example default
             */
            queue: string;
            /**
             * Stage Message
             * @description Human-readable stage
             * @example Converting page 84 of 200
             */
            stage_message: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "fetching" | "converting" | "rendering" | "done" | "failed" | "needs_user_action" | "expired";
            /**
             * Truncated
             * @description True when part of the input or output was cut
             * @default false
             */
            truncated: boolean;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Warnings
             * @description Canonical warning codes the conversion emitted, first-seen order (see GET /v1/warnings)
             */
            warnings?: string[];
            /**
             * Warnings Count
             * @description Number of warnings the conversion emitted
             * @default 0
             */
            warnings_count: number;
        };
        /** LimitsOut */
        LimitsOut: {
            /** Max Audio Seconds */
            max_audio_seconds: number;
            /** Max Pages */
            max_pages: number;
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Max Url Bytes */
            max_url_bytes: number;
            /** Retention Hours */
            retention_hours: number;
        };
        /** LinksOut */
        LinksOut: {
            /**
             * Events
             * @example /v1/jobs/job_7Kx2mQp9Lw3nRt5vYb8cDe/events
             */
            events: string;
            /**
             * Result
             * @example /v1/jobs/job_7Kx2mQp9Lw3nRt5vYb8cDe/result?profile=rag&format=md
             */
            result: string;
            /**
             * Self
             * @example /v1/jobs/job_7Kx2mQp9Lw3nRt5vYb8cDe
             */
            self: string;
        };
        /** ReadyOut */
        ReadyOut: {
            /**
             * Checks
             * @example {
             *       "database": true,
             *       "state": true,
             *       "workers": true
             *     }
             */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * SupplyCaptions
         * @description Caption JSON supplied by the browser extension for a needs_user_action job.
         */
        SupplyCaptions: {
            /** Captions */
            captions: {
                [key: string]: unknown;
            }[];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** WarningCodeOut */
        WarningCodeOut: {
            /**
             * Aliases
             * @description Retired spellings that still normalize to this code
             */
            aliases: string[];
            /**
             * Code
             * @example encoding_uncertain
             */
            code: string;
            /** Description */
            description: string;
            /**
             * Family
             * @example core
             */
            family: string;
            /**
             * Severity
             * @description Default severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /**
             * Suggestion
             * @description What the user can do about it
             */
            suggestion: string;
            /**
             * Truncates
             * @description True when this warning means content was cut (sets `truncated`)
             */
            truncates: boolean;
        };
        /**
         * WarningsOut
         * @description The warning code registry (`intomd.warnings.codes`).
         */
        WarningsOut: {
            /** Warnings */
            warnings: components["schemas"]["WarningCodeOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A dependency is down; `checks` says which. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: {
                /** @description Result format when `wait` returns a result: md, json, txt, zip */
                format?: string;
                /** @description Block up to this many seconds (max 60) and return the result */
                wait?: number;
            };
            header?: {
                /** @description Repeat-safe creation: the same key (per caller) returns the same job */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertUrlRequest"];
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to convert
                     */
                    file: string;
                    /**
                     * @description JSON object: ConvertOptionsIn fields, `profile`, and dotted overrides
                     * @example {"profile": "rag", "chunks.chunk_tokens": 512, "max_pages": 200}
                     */
                    options?: string;
                    /** @enum {string} */
                    profile?: "full" | "compact" | "rag" | "agent";
                };
            };
        };
        responses: {
            /** @description Deduplicated: an existing finished job with the same input and options. With `wait`, the rendered result itself when the job finished in time (job envelope in `X-Intomd-Job`). */
            200: {
                headers: {
                    /** @description Compact JobOut JSON (wait results only) */
                    "X-Intomd-Job"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                    "text/markdown": string;
                };
            };
            /** @description Job accepted */
            202: {
                headers: {
                    /** @description Requests allowed in the most restrictive window checked */
                    "X-RateLimit-Limit"?: number;
                    /** @description Requests left in that window */
                    "X-RateLimit-Remaining"?: number;
                    /** @description Unix time when the window resets */
                    "X-RateLimit-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `turnstile_required`: A Turnstile token is required for URL jobs on this instance. `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `turnstile_failed`: The Turnstile token was rejected. `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `input_too_large`: Upload or fetched body over the caller's cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unsupported_media_type`: Executable or unsupported input. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `url_blocked`: The URL (or a URL a converter asked for) failed the SSRF guard. `platform_disabled`: The site is disabled by this instance's platform policy. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`: Too many requests, jobs, or concurrent jobs; see Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `conversion_failed`: Every converter in the chain failed. `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_implemented`: The format exists in the contract but is not built yet (docx). */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `fetch_failed`: The URL could not be fetched. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `queue_unavailable`: The queue is down or the instance is at its active-job cap. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `timeout`: The conversion exceeded its time limit. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    fetchNodeClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchNodeClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchNodeClaimResponse"];
                };
            };
            /** @description The queue is empty */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`: Too many requests, jobs, or concurrent jobs; see Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    fetchNodeFail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchNodeFail"];
            };
        };
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    fetchNodeHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchNodeHeartbeat"];
            };
        };
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    fetchNodeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    claim_token: string;
                    /** Format: binary */
                    media: string;
                    /** @description JSON: title, uploader, duration, ... */
                    meta?: string;
                };
            };
        };
        responses: {
            /** @description Accepted for conversion */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `input_too_large`: Upload or fetched body over the caller's cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unsupported_media_type`: Executable or unsupported input. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `queue_unavailable`: The queue is down or the instance is at its active-job cap. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purged */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`: Too many requests, jobs, or concurrent jobs; see Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamJobEvents: {
        parameters: {
            query?: {
                /** @description Alternative to the Last-Event-ID header */
                last_event_id?: number | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: progress
                     *     id: 4
                     *     data: {"progress":42,"stage_message":"Converting page 84 of 200"}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`: Too many requests, jobs, or concurrent jobs; see Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobResult: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response; other query keys are profile overrides */
                cursor?: string | null;
                /** @description md | json | txt | zip | docx (501) */
                format?: string;
                /** @description full | compact | rag | agent (default: the job's profile) */
                profile?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rendered result */
            200: {
                headers: {
                    /** @description true when content was cut */
                    "X-Intomd-Truncated"?: string;
                    /** @description Number of warnings */
                    "X-Intomd-Warnings"?: number;
                    /** @description Token count of the body */
                    "X-Markdown-Tokens"?: number;
                    /** @description Requests allowed in the most restrictive window checked */
                    "X-RateLimit-Limit"?: number;
                    /** @description Requests left in that window */
                    "X-RateLimit-Remaining"?: number;
                    /** @description Unix time when the window resets */
                    "X-RateLimit-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "application/zip": string;
                    /**
                     * @example ---
                     *     title: Notes
                     */
                    "text/markdown": string;
                    "text/plain": string;
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `job_not_ready`: The job has not reached the state this call needs. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`: Too many requests, jobs, or concurrent jobs; see Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_implemented`: The format exists in the contract but is not built yet (docx). */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    supplyJobInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplyCaptions"];
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unauthorized`: Missing or unknown API key, or bad fetch-node secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `forbidden`: The key or node may not do this (for example residential fetches). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `not_found`: Unknown job, attachment, or route. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `job_not_ready`: The job has not reached the state this call needs. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `input_too_large`: Upload or fetched body over the caller's cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `unsupported_media_type`: Executable or unsupported input. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `queue_unavailable`: The queue is down or the instance is at its active-job cap. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWarningCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarningsOut"];
                };
            };
            /** @description `invalid_request`: Malformed body, unknown option, or invalid profile override. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `internal_error`: Unexpected server error (logged with the request id). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
