// Regenerates src/openapi.d.ts from docs/api/openapi.json (spec part4 4.5.1: types come from the OpenAPI document).
// `node scripts/generate.mjs` writes the file; `node scripts/generate.mjs --check` exits 1 when it is stale.
// test/openapi-drift.test.ts runs the same check under `pnpm test`, so CI fails on drift.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

export const SPEC_PATH = fileURLToPath(new URL("../../../docs/api/openapi.json", import.meta.url));
export const OUT_PATH = fileURLToPath(new URL("../src/openapi.d.ts", import.meta.url));

const HEADER =
  "// GENERATED by packages/sdk-ts/scripts/generate.mjs from docs/api/openapi.json. Do not edit.\n" +
  "// Regenerate: `uv run python apps/api/scripts/export_openapi.py && pnpm -F @ezmd/sdk generate`.\n\n";

/** Renders the TypeScript declarations for the committed OpenAPI document. */
export async function render() {
  const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8"));
  const ast = await openapiTS(spec, { alphabetize: true });
  return HEADER + astToString(ast).replace(/\r\n/g, "\n");
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  const next = await render();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUT_PATH, "utf8");
    } catch {
      // missing counts as stale
    }
    if (current !== next) {
      console.error("generate: src/openapi.d.ts is stale; run `pnpm -F @ezmd/sdk generate`.");
      process.exit(1);
    }
    console.log("generate: src/openapi.d.ts is up to date.");
  } else {
    writeFileSync(OUT_PATH, next);
    console.log("generate: wrote src/openapi.d.ts");
  }
}
