"""EDGAR filing index pages (`<accession>-index.html`) and full-text search results (part2 12c step 5).

The index page is generated by the SEC and has a stable structure: `#formName`, `#secNum`, `.infoHead` /
`.info` pairs (Filing Date, Accepted, Period of Report, Items), `.companyName`, `.identInfo`, and
`table.tableFile` tables (Document Format Files, Data Files) with Seq, Description, Document, Type, Size.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urljoin

from intomd.ir import Block, Heading, InlineSpan, ListBlock, ListItem, Provenance, Table, TableCell
from intomd_converters.web.dom import HtmlElement, body_of, collapse, decode_html, parse_html, tag_of

SEC_BASE = "https://www.sec.gov/"
_FORM = re.compile(r"form\s+(\S+)", re.I)
_CIK = re.compile(r"CIK\s*:?\s*(\d{1,10})", re.I)
_ACC = re.compile(r"\d{10}-\d{2}-\d{6}")
_ROLE = re.compile(r"\(([A-Za-z ]{2,30})\)\s*$")
MAX_SEARCH_ROWS = 100


@dataclass(frozen=True, slots=True)
class IndexDoc:
    seq: str
    description: str
    name: str
    url: str
    type: str
    size: str
    inline_xbrl: bool = False


@dataclass(frozen=True, slots=True)
class Filer:
    """One `.filerDiv` block: the company, its role on this filing, identifiers, and addresses."""

    name: str
    role: str | None
    cik: str | None
    ident: str | None
    addresses: tuple[tuple[str, str], ...] = ()


@dataclass(slots=True)
class FilingIndex:
    form: str | None = None
    form_description: str | None = None
    accession: str | None = None
    info: dict[str, str] = field(default_factory=dict)
    items: list[str] = field(default_factory=list)
    company: str | None = None
    cik: str | None = None
    ident: str | None = None
    filers: list[Filer] = field(default_factory=list)
    documents: list[IndexDoc] = field(default_factory=list)
    data_files: list[IndexDoc] = field(default_factory=list)

    @property
    def filed(self) -> str | None:
        return self.info.get("Filing Date")

    @property
    def period(self) -> str | None:
        return self.info.get("Period of Report")

    def primary(self) -> IndexDoc | None:
        """Seq 1, the main document of the submission."""
        for d in self.documents:
            if d.seq == "1":
                return d
        return self.documents[0] if self.documents else None

    def exhibits(self) -> list[IndexDoc]:
        return [d for d in self.documents if d.type.upper().startswith("EX-")]


def is_index_page(root: HtmlElement) -> bool:
    return root.find(".//div[@id='formName']") is not None and root.find(".//table[@class='tableFile']") is not None


def _text(el: HtmlElement | None) -> str:
    return collapse(el.text_content() or "") if el is not None else ""


def _real_url(href: str) -> str:
    """The inline viewer link `/ix?doc=/Archives/...` points at the document itself."""
    if href.startswith("/ix?doc="):
        href = href[len("/ix?doc=") :]
    return urljoin(SEC_BASE, href)


def _docs(table: HtmlElement) -> list[IndexDoc]:
    out: list[IndexDoc] = []
    for tr in table.iter("tr"):
        cells = [c for c in tr if tag_of(c) == "td"]
        if len(cells) < 5:
            continue
        link = cells[2].find(".//a")
        name = _text(link) if link is not None else _text(cells[2])
        if not name:
            continue
        href = _real_url((link.get("href") or "").strip()) if link is not None else ""
        ixbrl = "ixbrl" in _text(cells[2]).lower().replace(name.lower(), "")
        out.append(IndexDoc(_text(cells[0]), _text(cells[1]), name, href, _text(cells[3]), _text(cells[4]), ixbrl))
    return out


def _filer(div: HtmlElement) -> Filer | None:
    company = div.find(".//span[@class='companyName']")
    if company is None:
        return None
    raw_name = collapse(company.text or "")
    m = _ROLE.search(raw_name)
    name = raw_name[: m.start()].strip() if m else raw_name
    cik = _CIK.search(_text(company))
    ident = div.find(".//p[@class='identInfo']")
    if ident is not None:
        for br in ident.iter("br"):
            br.tail = "; " + (br.tail or "")
    addresses: list[tuple[str, str]] = []
    for mailer in div.iter("div"):
        if mailer.get("class") != "mailer":
            continue
        label = collapse(mailer.text or "")
        parts = [_text(sp) for sp in mailer if tag_of(sp) == "span" and sp.get("class") == "mailerAddress"]
        value = ", ".join(p for p in parts if p)
        if label and value:
            addresses.append((label, value))
    return Filer(
        name=name,
        role=m.group(1) if m else None,
        cik=str(int(cik.group(1))) if cik else None,
        ident=_text(ident) or None,
        addresses=tuple(addresses),
    )


def parse_index(raw: bytes, headers: dict[str, str] | None = None) -> FilingIndex | None:
    text, _enc, _conf = decode_html(raw, headers)
    root = parse_html(text)
    if not is_index_page(root):
        return None
    idx = FilingIndex()
    form_el = root.find(".//div[@id='formName']")
    form_text = _text(form_el)
    m = _FORM.search(form_text)
    if m is not None:
        idx.form = m.group(1)
        rest = form_text[m.end() :]
        desc = rest.split("-", 1)[1] if "-" in rest else ""
        idx.form_description = desc.strip(" :") or None
    acc = _ACC.search(_text(root.find(".//div[@id='secNum']")))
    idx.accession = acc.group(0) if acc else None
    for head in root.iter("div"):
        if head.get("class") == "infoHead":
            value = head.getnext()
            if value is not None and value.get("class") == "info":
                if _text(head) == "Items":
                    idx.items = [collapse(t) for t in value.itertext() if collapse(t)]
                else:
                    idx.info.setdefault(_text(head), _text(value))
    idx.filers = [f for f in (_filer(div) for div in root.iter("div") if div.get("class") == "filerDiv") if f]
    if idx.filers:
        idx.company, idx.cik, idx.ident = idx.filers[0].name, idx.filers[0].cik, idx.filers[0].ident
    for table in body_of(root).iter("table"):
        if table.get("class") != "tableFile":
            continue
        docs = _docs(table)
        if (table.get("summary") or "").lower().startswith("data"):
            idx.data_files.extend(docs)
        else:
            idx.documents.extend(docs)
    return idx


def _cell(text: str, row: int, col: int, *, header: bool = False, href: str | None = None) -> TableCell:
    return TableCell(
        spans=[InlineSpan(text=text, href=href or None)] if text else [], row=row, col=col, is_header=header
    )


def kv_table(rows: list[tuple[str, str]], prov: Provenance) -> Table:
    cells = [_cell("Field", 0, 0, header=True), _cell("Value", 0, 1, header=True)]
    for r, (k, v) in enumerate(rows, start=1):
        cells += [_cell(k, r, 0), _cell(v, r, 1)]
    return Table(cells=cells, n_rows=len(rows) + 1, n_cols=2, header_rows=1, provenance=prov)


def docs_table(docs: list[IndexDoc], prov: Provenance) -> Table:
    heads = ("Seq", "Description", "Document", "Type", "Size")
    cells = [_cell(h, 0, c, header=True) for c, h in enumerate(heads)]
    for r, d in enumerate(docs, start=1):
        for c, v in enumerate((d.seq, d.description, d.name, d.type, d.size)):
            cell = _cell(v, r, c, href=d.url if c == 2 else None)
            if c == 2 and d.inline_xbrl:
                cell = cell.model_copy(update={"spans": [*cell.spans, InlineSpan(text=" (iXBRL)")]})
            cells.append(cell)
    return Table(cells=cells, n_rows=len(docs) + 1, n_cols=len(heads), header_rows=1, provenance=prov)


def index_blocks(idx: FilingIndex, source: str, *, with_title: bool) -> list[Block]:
    """H1 (optional), the filing facts, the items list, and the documents and data-file tables."""

    def prov(path: str) -> Provenance:
        return Provenance(source=source, path=path, source_id=idx.accession, engine="specialized.edgar")

    out: list[Block] = []
    if with_title:
        title = " ".join(p for p in (idx.company, idx.form, idx.period) if p) or "EDGAR filing"
        out.append(Heading(level=1, spans=[InlineSpan(text=title)], provenance=prov("index")))
        rows = [("Form", idx.form or "")]
        if idx.form_description:
            rows.append(("Form description", idx.form_description))
        rows.append(("Accession", idx.accession or ""))
        rows += [(k, v) for k, v in idx.info.items() if v]
        for f in idx.filers:
            role = f.role or "Company"
            rows.append((role, f.name + (f" (CIK {f.cik})" if f.cik else "")))
            rows += [(f"{role} {label.lower()}", value) for label, value in f.addresses]
            if f.ident:
                rows.append((f"{role} details", f.ident))
        out.append(Heading(level=2, spans=[InlineSpan(text="Filing")], provenance=prov("index")))
        out.append(kv_table([(k, v) for k, v in rows if v], prov("index")))
        if idx.items:
            items = [ListItem(spans=[InlineSpan(text=t)]) for t in idx.items]
            out.append(Heading(level=2, spans=[InlineSpan(text="Items")], provenance=prov("index/items")))
            out.append(ListBlock(items=items, provenance=prov("index/items")))
    if idx.documents:
        label = "Documents" if with_title else "Exhibits and documents"
        out.append(Heading(level=2, spans=[InlineSpan(text=label)], provenance=prov("index/documents")))
        out.append(docs_table(idx.documents, prov("index/documents")))
    if idx.data_files:
        out.append(Heading(level=2, spans=[InlineSpan(text="Data files")], provenance=prov("index/data")))
        out.append(docs_table(idx.data_files, prov("index/data")))
    return out


def search_blocks(raw: bytes, source: str, query: str | None) -> list[Block] | None:
    """Full-text search JSON (`efts.sec.gov/LATEST/search-index`) as a table of filings, not converted."""
    try:
        data: Any = json.loads(raw)
    except ValueError:
        return None
    hits = data.get("hits", {}).get("hits") if isinstance(data, dict) else None
    if not isinstance(hits, list):
        return None
    prov = Provenance(source=source, path="search", engine="specialized.edgar")
    heads = ("Company", "Form", "Filed", "Period", "Accession", "Document")
    cells = [_cell(h, 0, c, header=True) for c, h in enumerate(heads)]
    rows = 0
    for hit in hits[:MAX_SEARCH_ROWS]:
        src = hit.get("_source") if isinstance(hit, dict) else None
        if not isinstance(src, dict):
            continue
        rows += 1
        names = src.get("display_names") or []
        company = "; ".join(str(n) for n in names) if isinstance(names, list) else str(names)
        hit_id = str(hit.get("_id") or "")
        adsh = str(src.get("adsh") or hit_id.split(":", 1)[0])
        doc = hit_id.split(":", 1)[1] if ":" in hit_id else ""
        ciks = src.get("ciks") or []
        cik = str(int(ciks[0])) if isinstance(ciks, list) and ciks and str(ciks[0]).isdigit() else ""
        url = f"{SEC_BASE}Archives/edgar/data/{cik}/{adsh.replace('-', '')}/{doc}" if cik and doc else None
        values = (company, src.get("form"), src.get("file_date"), src.get("period_ending"), adsh, doc)
        for c, v in enumerate(values):
            cells.append(_cell(str(v or ""), rows, c, href=url if c == 5 else None))
    title = f"EDGAR full-text search: {query}" if query else "EDGAR full-text search"
    out: list[Block] = [Heading(level=1, spans=[InlineSpan(text=title)], provenance=prov)]
    if rows:
        out.append(Table(cells=cells, n_rows=rows + 1, n_cols=len(heads), header_rows=1, provenance=prov))
    return out
