"""Rewrite the environment variable table in docs/selfhost.md from ezmd_api.settings.Settings.

The table sits between the BEGIN/END markers below; everything else in the page is hand-written.
Sections come from the `# ---- Name ----` comments in settings.py. Descriptions come from the field's
`description` when it has one, otherwise from DESCRIPTIONS here. A test asserts the committed page is
current and that every field is described.
"""

from __future__ import annotations

import re
import sys
import types
import typing
from pathlib import Path
from typing import Any, Literal

from pydantic import SecretStr
from pydantic_core import PydanticUndefined

from ezmd_api import settings as settings_mod
from ezmd_api.settings import ENV_PREFIX, Settings

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "selfhost.md"
BEGIN = "<!-- BEGIN gen_env_doc (generated by tools/gen_env_doc.py; do not edit by hand) -->"
END = "<!-- END gen_env_doc -->"
PIPE_ESCAPED = chr(92) + "|"
_SECTION = re.compile(r"^\s*# ---- (.+?) ----\s*$")
_FIELD = re.compile(r"^    ([a-z_][a-z0-9_]*)\s*:")

# Defaults that depend on the machine are shown symbolically.
DEFAULT_OVERRIDES: dict[str, str] = {"data_dir": "`~/.ezmd`"}

DESCRIPTIONS: dict[str, str] = {
    "public_mode": "Public-instance mode. Requires `EZMD_JWT_SECRET` and `EZMD_KEY_PEPPER` of at least 32 bytes, "
    "requires a Turnstile challenge for URL jobs, and never deduplicates anonymous jobs across clients.",
    "public_url": "Externally visible base URL. Used for links in error documents and to decide whether "
    "cookies are marked `Secure`.",
    "data_dir": "Base directory for the default SQLite database and filesystem blob store.",
    "web_dist": (
        "Directory with the built web UI (`apps/web/dist`) to serve at `/`. Unset: `apps/web/dist` next to the "
        "source tree when present, else no UI. The compose stack defaults it to the image's `/app/apps/web/dist`."
    ),
    "scheduler_enabled": "Run the retention purge inside the API process. Compose sets `false` and runs the "
    "separate `purge` service instead.",
    "database_url": "Database URL. Unset: SQLite at `<data_dir>/ezmd.db`.",
    "blob_backend": "Where inputs, IR, and rendered results are stored: local filesystem or S3-compatible storage.",
    "blob_fs_root": "Root of the filesystem blob store. Unset: `<data_dir>/blobs`.",
    "s3_endpoint": "S3 endpoint URL (for MinIO or another S3-compatible service). Unset: the AWS default.",
    "s3_bucket": "S3 bucket name.",
    "s3_access_key": "S3 access key id (secret).",
    "s3_secret_key": "S3 secret access key (secret).",
    "s3_region": "S3 region.",
    "retention_hours": "Hours a job and its blobs are kept. `0` deletes the job on first result download "
    "(it is kept for at most one hour otherwise).",
    "purge_interval_s": "Seconds between retention purge runs.",
    "redis_url": "Redis URL for the RQ queues, job events, and rate limits. Compose builds it from "
    "`EZMD_REDIS_PASSWORD`.",
    "queue": "`rq` sends jobs to RQ workers; `inline` converts in the API process (development and tests).",
    "job_timeout_s": "Upper bound on any job's wall-clock time. Per-queue timeouts (default 600 s, media "
    "3600 s, fetch 120 s) are capped by it.",
    "job_mem_mb": "Address-space limit (RLIMIT_AS) for a conversion child process on the default queue.",
    "media_job_mem_mb": "Address-space limit for a conversion child process on the media queue (Phase 2).",
    "worker_default_concurrency": "Default-queue worker slots. Used to size the global active-job cap.",
    "worker_media_concurrency": "Media-queue worker slots. Used to size the global active-job cap.",
    "max_active_jobs": "Global cap on queued and running jobs; beyond it the API answers `queue_unavailable`. "
    "Unset: 2 x (default + media worker slots).",
    "residential_wait_seconds": "How long a residential-only fetch job waits while no fetch node is online "
    "before it asks the user to upload the file instead (`needs_user_action`).",
    "max_result_bytes": "Largest IR JSON a conversion child process may hand back, in bytes; larger results fail "
    "with `result_too_large`.",
    "anon_max_upload_mb": "Maximum upload size for anonymous callers, in MB.",
    "anon_max_html_mb": "Maximum size of a fetched page for anonymous callers, in MB.",
    "anon_max_duration_s": "Maximum media duration for anonymous callers, in seconds.",
    "anon_max_pages": "Maximum pages converted per document.",
    "anon_ratelimit_max": "Job creations allowed per client per window.",
    "anon_ratelimit_window_s": "Length of the job-creation rate-limit window, in seconds.",
    "anon_daily_max": "Job creations allowed per client per day.",
    "anon_concurrency": "Active (queued or running) jobs allowed per anonymous client.",
    "anon_result_ratelimit_max": "Result and attachment fetches allowed per client per minute.",
    "anon_sse_max": "Concurrent SSE connections allowed per client.",
    "fetch_node_claims_per_minute": "Job claims allowed per fetch node per minute.",
    "require_api_key": "Reject requests without a valid `X-API-Key` header.",
    "key_pepper": "Secret pepper for hashing API keys (secret). At least 32 bytes in public mode.",
    "jwt_secret": "Secret for signing the short-lived challenge cookie (secret). At least 32 bytes in public mode.",
    "ip_hash_salt": "Salt for client IP hashes (secret). Unset: falls back to the key pepper, then a fixed local salt.",
    "turnstile_sitekey": "Cloudflare Turnstile site key shown by the web UI.",
    "turnstile_secret": "Cloudflare Turnstile secret (secret). Setting it turns the challenge on for URL jobs.",
    "turnstile_required_for_fetch": "Require a Turnstile challenge for URL jobs even outside public mode.",
    "turnstile_jwt_ttl_s": "Lifetime of the challenge cookie issued after a successful Turnstile check, in seconds.",
    "allow_private_networks": "Let URL jobs reach private, loopback, and link-local addresses. Leave `false` "
    "unless the instance is on a trusted network.",
    "platforms_file": "Path to a `platforms.toml` that marks hosts `sanctioned`, `residential_only`, or `disabled`.",
    "fetch_node_secret": "Shared secret fetch nodes send as a bearer token (secret, at least 16 characters). "
    "Unset: the fetch-node endpoints are not mounted.",
    "fetch_node_cidr": "Comma-separated CIDRs fetch nodes may connect from (the Tailscale range by default).",
    "cors_origins": "Comma-separated origins allowed by CORS. Empty: same-origin only.",
    "trust_proxy_header": "Header carrying the client IP, honored only when the TCP peer is in "
    "`EZMD_TRUSTED_PROXIES`. Compose sets `X-Real-IP` (Caddy overwrites it, Cloudflare-aware). "
    "Empty: the TCP peer address. See Client IP above.",
    "trusted_proxies": "Comma-separated CIDRs of the reverse proxies allowed to set that header. Compose "
    "sets the private ranges (only containers on `internal` reach the API).",
    "log_level": "Log level.",
    "log_format": "`json` (one object per line) or `text`.",
}


def sections() -> dict[str, str]:
    """Map each Settings field to the `# ---- Section ----` comment above it in settings.py."""
    source = Path(settings_mod.__file__).read_text(encoding="utf-8").splitlines()
    current = "General"
    out: dict[str, str] = {}
    in_class = False
    for line in source:
        if line.startswith("class Settings("):
            in_class = True
            continue
        if in_class and line and not line.startswith(" "):
            break
        if not in_class:
            continue
        m = _SECTION.match(line)
        if m:
            current = m.group(1)
            continue
        f = _FIELD.match(line)
        if f and f.group(1) in Settings.model_fields:
            out[f.group(1)] = current
    return out


def _type_name(tp: Any) -> str:
    origin = typing.get_origin(tp)
    if origin is Literal:
        return " / ".join(str(a) for a in typing.get_args(tp))
    if origin is typing.Union or origin is types.UnionType:
        return " / ".join(_type_name(a) for a in typing.get_args(tp) if a is not type(None))
    if origin is typing.Annotated:
        return _type_name(typing.get_args(tp)[0])
    if origin is list:
        return "comma list"
    if tp is SecretStr:
        return "secret"
    if tp is Path:
        return "path"
    return getattr(tp, "__name__", str(tp))


def _default(name: str) -> str:
    if name in DEFAULT_OVERRIDES:
        return DEFAULT_OVERRIDES[name]
    info = Settings.model_fields[name]
    value = info.default_factory() if info.default_factory is not None else info.default  # type: ignore[call-arg]
    if value is PydanticUndefined or value is None:
        return "unset"
    if isinstance(value, SecretStr):
        value = value.get_secret_value()
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return f"`{','.join(value)}`" if value else "empty"
    if value == "":
        return "empty"
    return f"`{value}`"


def missing_descriptions() -> list[str]:
    return [n for n, f in Settings.model_fields.items() if not (f.description or DESCRIPTIONS.get(n))]


def render_table() -> str:
    missing = missing_descriptions()
    if missing:
        raise SystemExit(f"Settings fields without a description: {', '.join(missing)}")
    by_section = sections()
    lines: list[str] = []
    last = None
    for name, info in Settings.model_fields.items():
        section = by_section.get(name, "General")
        if section != last:
            if last is not None:
                lines.append("")
            lines += [f"### {section}", "", "| Variable | Type | Default | Description |", "|---|---|---|---|"]
            last = section
        desc = (info.description or DESCRIPTIONS[name]).replace("|", PIPE_ESCAPED)
        type_name = _type_name(info.annotation).replace("|", PIPE_ESCAPED)
        lines.append(f"| `{ENV_PREFIX}{name.upper()}` | {type_name} | {_default(name)} | {desc} |")
    return "\n".join(lines)


def update(text: str) -> str:
    """Return `text` with the marker block replaced by the current table."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < start:
        raise SystemExit(f"{TARGET.name} is missing the gen_env_doc markers")
    return text[: start + len(BEGIN)] + "\n\n" + render_table() + "\n\n" + text[end:]


def main() -> int:
    text = TARGET.read_text(encoding="utf-8")
    TARGET.write_text(update(text), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(Settings.model_fields)} variables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
